### ISSUE TITLE
网页控制台看不到实例

### ISSUE THREAD

**Issue by Jadlokin-Scarlet** [Zaitonn/iPanel#13]
版本：[b851402](https://github.com/iPanelDev/iPanel/commit/b851402176b1201aaa9e0bdacc7d6da69424d65c)
系统：windows
![无标题](https://github.com/iPanelDev/iPanel/assets/32767557/5bf8b8a0-1b4b-4930-a18a-bdc8527a1f13)

**Comment by Zaitonn** [comment]
检查一下当前用户的权限等级是不是管理员

如果是助手或者只读的话需要设置可查看/管理的实例列表，否则不会显示出来
