### ISSUE TITLE
功能建议：支持数据库存储

### ISSUE THREAD

**Issue by Ranzeplay** [Zaitonn/iPanel#15]
将产生的诸如用户数据存储在数据库中
可以考虑使用Microsoft的EntityFramework Core

**Comment by Zaitonn** [comment]
可能需要一些时间😭....以前没怎么接触过数据库

<sup>*近期的重点还在Serein上，可能不会那么早考虑</sup>

**Comment by Ranzeplay** [comment]
了解了
