### ISSUE TITLE
测试、SDK、文档以及一些需求

### ISSUE THREAD

**Issue by AnzhiZhang** [Zaitonn/iPanel#4]
1. 我们目前有使用的意愿，参考了一下仓库开发记录和您本人的履历，请问能否加入测试，让该软件更可信，提高可用性
2. 是否考虑将前后端的核心部分、MCDR 插件单独开源一个项目，方便其他项目可以使用，例如 [aiocqhttp](https://github.com/nonebot/aiocqhttp) 和 [OneBot](https://github.com/botuniverse/onebot)
3. 项目的各协议能否提供相关文档，并确保稳定可靠的版本管理？这样方便他人二次开发，例如使用 MCDR 插件并另外开发前后端

**Comment by Zaitonn** [comment]
>请问能否加入测试，让该软件更可信，提高可用性

有这个想法，但是C#的单元测试我没怎么接触过，可能需要一定时间来完善:(

>是否考虑将前后端的核心部分、MCDR 插件单独开源一个项目，方便其他项目可以使用

这个考虑一下吧（可能就在不远的将来（咕

>项目的各协议能否提供相关文档，并确保稳定可靠的版本管理？这样方便他人二次开发，例如使用 MCDR 插件并另外开发前后端

文档将慢慢补全，因为这个项目是一年前立的项，而现在才刚刚填坑完，还来不及把文档补全；目前的文档只是先临时把使用方法丢上去，后面慢慢将文档改用docusaurus构建，就能实现比较好的版本管理

（也可以先参考一下源码的说，主要的数据包处理部分都在[iPanel/src/Core/Service at main](https://github.com/Zaitonn/iPanel/tree/main/src/Core/Service)

**Comment by Zaitonn** [comment]
>文档将慢慢补全

- 新的文档搞好了：https://ipanel.serein.cc/docs/development/intro/
  - 版本控制要等新建下一个版本才能用（

**Comment by AnzhiZhang** [comment]
> > 文档将慢慢补全
> 
> * 新的文档搞好了：https://ipanel.serein.cc/docs/development/intro/
>   
>   * 版本控制要等新建下一个版本才能用（

感谢，我看有好几个在线的文档，在 https://serein.cc/ 上还有一套文档，请问是否有计划整理一下这个生态和文档，方便用户查看和了解？没有找到文档中有关于**软件整体、生态和功能**的概述，只有“新时代极简服务器面板”，第一感觉是一个功能类似mcsm的软件，而且在功能的列表中也没有看到对于每一个功能的描述。对新用户了解这套软件不是很友好

**Comment by Zaitonn** [comment]
2.3即将发布
- 由于文档依赖更新（docusaurus `v2.4.1`→`3.0.0`），iPanel 2.1版本的文档因不兼容的格式太多，可能不会合并到下一个版本（2.3）的文档中，但是会保留该分支
- 目前已添加了十几个测试用例，但是还未全覆盖，这个最近会慢慢补全

~~为什么没有2.2？因为咕了然后重构了~~
