### ISSUE TITLE
Ubuntu Server 22.04上无法运行iPanel

### ISSUE THREAD

**Issue by KelvinZhang512** [Zaitonn/iPanel#8]
1、用微软官方的仓库安装好dotnet SDK 6.0.125；
2、根据iPanel文档切换至iPanel目录并执行dotnet run "./iPanel.dll"
3、终端报错：Couldn't find a project to run
![image](https://github.com/iPanelDev/iPanel/assets/48343945/a9ddeda1-d2ca-45eb-8802-db52c914aaf0)
![image](https://github.com/iPanelDev/iPanel/assets/48343945/ef43e9cc-a13b-42b7-aaae-1f8a2b5495f0)

**Comment by Zaitonn** [comment]
- 使用发布的二进制文件运行
  1. 从Releases下载对应系统版本的文件
  2. cd到解压后的目录，确保当前目录下有iPanel.dll这个文件
  3. 输入`dotnet run "./iPanel.dll"` 
- 使用源码编译运行
  1. 克隆源码
  2. cd到`iPanel`目录
  3. 输入`dotnet run`运行

**Comment by Zaitonn** [comment]
如果仍然不能运行的话请麻烦`ls`一下然后看看当前目录下有没有此dll文件

**Comment by KelvinZhang512** [comment]
Releases里的iPanel_2.3.0_linux-x64.zip解压出来以后并没有iPanel.dll，正在尝试克隆源码。

**Comment by Zaitonn** [comment]
很抱歉没注意到 要不你试试直接dotnet "./iPanel"能不能运行

**Comment by KelvinZhang512** [comment]
之前已尝试过，无法运行。

**Comment by KelvinZhang512** [comment]
克隆源码并进入目录依旧无法运行。
![image](https://github.com/iPanelDev/iPanel/assets/48343945/7c031653-6a42-4243-8441-a818fc713479)

**Comment by Zaitonn** [comment]
cd到当前目录下的iPanel文件夹内再编译

或者尝试在那个Releases的文件目录下`chmod +x ./iPanel`后直接用`./iPanel`运行

**Comment by Zaitonn** [comment]
https://ipaneldev.github.io/docs/guide/quickStart/#linux--macos
